# Generated by Django 4.2.30 on 2026-04-20 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='number',
        ),
        migrations.AddField(
            model_name='booking',
            name='guests',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='hotel',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='image_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='hotel',
            name='stars',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='room',
            name='is_available',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='room',
            name='room_number',
            field=models.CharField(default=0, max_length=10),
        ),
        migrations.AddField(
            model_name='room',
            name='room_type',
            field=models.CharField(default='not assigned', max_length=50),
        ),
    ]
